import type { Metadata } from "next";
import { Indie_Flower } from "next/font/google";
import "./globals.css";

const indie = Indie_Flower({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-indie",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={indie.className}>{children}</body>
    </html>
  );
}
